spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    generate-ddl: true

    properties:
      hibernate:
        format_sql: true
